spring:
  datasource:
    url: jdbc:mysql:///web03           # 数据库连接地址（简写格式，默认本地3306端口）
    username: root                       # 数据库登录用户名
    password: MYSQL123

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support,JdbcTransactionManager:debug:

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-wen0
    region: cn-beijing